search:
  context: 
      location:
        country:
          code:
            - code: IND
              description: Represents the country
              reference: <PR/Issue/Discussion Links md format text>
        city:
          code:
            - code: std:080
              description: >-
                Represent the city code that identifies the cities. In case of
                '*' it will fetch all the cities where service is being
                provided.
              reference: <PR/Issue/Discussion Links md format text
      action:
        code: search 
         description: >-
                Represent the city code that identifies the cities. In case of
                '*' it will fetch all the cities where service is being
                provided.
        reference: <PR/Issue/Discussion Links md format text
        code: on_search 
         description: >-
                Represent the city code that identifies the cities. In case of
                '*' it will fetch all the cities where service is being
                provided.
        reference: <PR/Issue/Discussion Links md format text
  message:
      intent:
        category:
          descriptor:
            code:
              - code: PERSONAL_LOAN
                description: >-
                  Describes an unsecured credit provided by financial
                  institutions based on criteria like employment history,
                  repayment capacity, income level, profession and credit
                  history
                reference: <PR/Issue/Discussion Links md format text
              - code: PURCHASE_FINANCE
                description: >-
                  Describes a digital journey where customers can discover the
                  best "loan offers" on the buyer apps to buy the products on
                  credit.
                reference: <PR/Issue/Discussion Links md format text
on_search:
 context: *ref_0
 message:
      catalog:
        providers:
          items: &ref_2
            descriptor:
              code:
                - code: LOAN
                  description: Describes item descriptor code
                  reference: <PR/Issue/Discussion Links md format text
            xinput:
              form_response:
                status:
                  - code: PENDING
                    description: Describes the current state of the request.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: APPROVED
                    description: Describes the current state of the request.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: REJECTED
                    description: Describes the current state of the request.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: EXPIRED
                    description: Describes the current state of the request.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: SUCCESS
                    description: When form gets submitted successfully
                    reference: <PR/Issue/Discussion Links md format text
              head:
                headings:
                  - code: EMANDATE
                    description: Describes form heading.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: ESIGN
                    description: Describes form heading.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: MERCHANT_AND_PRDOUCT_DEATILS
                    description: Describes form heading.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: PERSONAL_INFORMATION
                    description: Describes form heading.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: SET_LOAN_AMOUNT
                    description: Describes form heading.
                    reference: <PR/Issue/Discussion Links md format text
                  - code: KYC
                    description: Describes form heading.
                    reference: <PR/Issue/Discussion Links md format text
          categories: *ref_1

        