calls:
  - config: "search"
    mode: "ASYNC"
  - config: "select_loan"
    mode: "SYNC"
  - config: "select_approval"
    mode: "ASYNC"
  - config: "select_after_amount_adjust"
    mode: "SYNC"
  - config: "init_kyc"
    mode: "ASYNC"
  - config: "init_personal_loan"
    mode: "SYNC"
  - config: "init_with_account_details"
    mode: "SYNC"
  - config: "confirm"
    mode: "SYNC"
  - config: "status"
    mode: "SYNC"
  - config: "update"
    mode: "SYNC"

  - config: "on_search"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_select_loan"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_select_approval"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_select_after_amount_adjust"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_init_kyc"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_init_personal_loan"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_init_with_account_details"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_confirm"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_status"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_update"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
