calls:
  - config: "search_bus"
    mode: "ASYNC"
  - config: "search_station"
    mode: "SYNC"
  - config: "search_service"
    mode: "ASYNC"
  - config: "select"
    mode: "ASYNC"
  - config: "init"
    mode: "SYNC"
  - config: "confirm"
    mode: "ASYNC"

  - config: "on_search_bus"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
  - config: "on_search_station"
    endpoint: "mapper/ondc"
    mode: "SYNC"
  - config: "on_select"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
  - config: "on_init"
    endpoint: "mapper/ondc"
    mode: "SYNC"
  - config: "on_confirm"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
