calls:
  - config: "search_route"
    mode: "ASYNC"
  - config: "search_trip"
    mode: "SYNC"
  - config: "select"
    mode: "ASYNC"
  - config: "init"
    mode: "SYNC"
  - config: "confirm"
    mode: "ASYNC"

  - config: "on_search_route"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
  - config: "on_search_trip"
    endpoint: "mapper/ondc"
    mode: "SYNC"
  - config: "on_select"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
  - config: "on_init"
    endpoint: "mapper/ondc"
    mode: "SYNC"
  - config: "on_confirm"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
