calls:
  - config: "search"
    mode: "ASYNC"
    callback:
      config: "on_search"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "select_1"
    mode: "SYNC"
  - config: "select_2"
    mode: "ASYNC"
  - config: "init"
    mode: "ASYNC"
  - config: "confirm"
    mode: "SYNC"
  - config: "status"
    mode: "SYNC"
  - config: "update"
    mode: "SYNC"

  - config: "on_search"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_select_1"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_select_2"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_init"
    endpoint: "mapper/ondc"
    mode: "ASYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_confirm"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_status"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
  - config: "on_update"
    endpoint: "mapper/ondc"
    mode: "SYNC"
    unsolicitedEndpoint: "mapper/unsolicited"
