flows:
  - summary: InterCity(Bus) - Station Code Based Flow
    id: intercity-flow-1
    shouldDispaly: false
    domain: ONDC:TRV12
    sessionData:
      version: "2.0.0"
    protocol:
      $ref: ./intercity-flow-1/protocolMapping.yaml#/protocol
    calls:
      $ref: ./intercity-flow-1/calls.yaml#/calls
